project_name: "SoccerNet_YOLO11_MEDIUM"

paths:
  raw_data: "./dataset/raw_data"
  yolo_dataset: "./dataset/yolo"
  model_weights: "https://huggingface.co/aabyzov/easychamp-player-detection-yolov8/resolve/main/player_detection_best.pt"
  output_submission: "./output/submissions"
  output_val: "./output/validation"

training:
  model_size: "yolo11m.pt"
  epochs: 50
  imgsz: 1280
  batch_size: 8
  device: 0

val:
  split: "test"
  imgsz: 1280
  classes: [1,2,3]
  batch_size: 8
  conf_threshold: 0.001
  iou_threshold: 0.6

