project_name: "SoccerNet_YOLO8_X"

device: 0

paths:
  raw_data: "./dataset/raw_data"
  split: "test"
  yolo_dataset: "./dataset/yolo"
  model_weights: "https://huggingface.co/aabyzov/easychamp-player-detection-yolov8/resolve/main/player_detection_best.pt"
  output_submission: "./output/submissions"
  output_val: "./output/validation"
  temp_tracker_yaml: "./output/temp_botsort.yaml"