test_name: "track_prova_contest_runner"
eval: True
single_cls: true
specific_video:
conf_threshold: 0.2
iou_threshold: 0.7
display: false
display_width: 1280
half: True
show: False
imgsz: 1088
stream: True
verbose: False
persist: True
agnostic_nms: True
classes: [0]
random: False
max_video: 5

field_det_settings:
    debug: true
    debug_mosaic: false

    hsv_lower: [35, 27, 40]
    hsv_upper: [95, 200, 200]

    alpha_smooth: 0.7
    kernel_erode_size: 18
    kernel_dilate_size: 13
    kernel_close_size: 30
    morph_iterations: 2
    binary_threshold: 100
    min_area_ratio: 0.01
    poly_epsilon: 0.01

    pixel_check_radius: 5
    pixel_check_ratio: 0.1
    bottom_zone_ratio: 0.80
    strong_conf_thresh: 0.75
    safe_zone_dist: 30

    clipping_margin: 5

    pixel_check_offset: 10

    thresh_clipping: -5.0
    thresh_bottom: 5.0
    thresh_standard: -2.0

tracker_settings:
    tracker_type: "botsort"
    track_high_thresh: 0.25
    track_low_thresh: 0.2
    new_track_thresh: 0.30
    track_buffer: 150
    match_thresh: 0.9
    gmc_method: "sparseOptFlow"
    proximity_thresh: 0.90
    appearance_thresh: 0.30
    with_reid: True
    fuse_score: True
    reid_model: "osnet_x0_25_msmt17.pt"
    model: auto