test_name: "track_3"
eval: True
conf_threshold: 0.2
iou_threshold: 0.7
display: True
display_width: 1280
half: True
show: False
imgsz: 1088
stream: True
verbose: False
persist: True
agnostic_nms: True
classes: [1,2,3]
max_video: 1

tracker_settings:
    tracker_type: botsort
    track_high_thresh: 0.75
    track_low_thresh: 0.65
    new_track_thresh: 0.80
    track_buffer: 300
    match_thresh: 0.8
    gmc_method: sparseOptFlow
    proximity_thresh: 0.70
    appearance_thresh: 0.30
    with_reid: False
    fuse_score: False
    reid_model: osnet_x0_25_msmt17.pt
    model: auto